### ISSUE TITLE
Invalid java specification from compile_package_jars()

### ISSUE THREAD

**Issue by jmcmillan0110** [javierluraschi/sparkhello#4]
Hello,

I am having a problem with `compile_package_jars()` . The error I get is `invalid version specification ‘java’`. I am able to load the rJava package and the Java version is 1.8.0_131-b11. The $JAVA_HOME variable is `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64/jre`. The result of `SessionInfo()` is 
```
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
```
As a side note, is it possible to bypass `compile_package_jars()` completely and use a jar file compiled separately through sbt?

Thank you very much!

**Comment by javierluraschi** [comment]
@jmcmillan0110 Fixed in `sparklyr` with https://github.com/rstudio/sparklyr/pull/837, please install latest version using `devtools::install_github("rstudio/sparklyr")`.
